### ISSUE TITLE
Enum validation is missing

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/terraform-provider-zitadel#10]
Enums are currently not validated, the value is simply skipped and `terraform apply` succeeds.

Terraform doesn't directly support it, but it should nevertheless be possible [using constraints](https://github.com/hashicorp/terraform/issues/25283).

**Comment by stebenz** [comment]
Will have to test it, the "plan" step should work, but the applying of the resource should at least fail, as the ZITADEl API should have a validation.

**Comment by stebenz** [comment]
added ValidateDiagFunc functionality in v1.0.0-alpha.8 for several functions to validate enums in the "plan" step, so enums are checked and an error occurs if no supported value is used
