### ISSUE TITLE
Unable to obtain client_ secret for application

### ISSUE THREAD

**Issue by jinyangyang222** [zitadel/terraform-provider-zitadel#110]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

After creating the zitadel organization using Terraform, I can get the client_id of the application by defining outputs.tf, but cannot get client_ secret.

[
![0801](https://github.com/zitadel/terraform-provider-zitadel/assets/121534745/9a7db916-0d55-45ca-94be-f9d86171f64a)
](url)

### Describe your ideal solution

Please tell me how to obtain it.

### Version

v1.0.0-alpha.18

### Additional Context

no more

**Comment by eliobischof** [comment]
The ZITADEL API only returns the client secret when it is created. After that, there is no way to read the secret from the ZITADEL API anymore.

If you want to have the client secret in your Terraform state so you can reference it, either create a new app using Terraform or [import the resource by providing the secret](https://registry.terraform.io/providers/zitadel/zitadel/latest/docs/resources/application_api#import).

Please reopen the issue if this doesn't help.
