### ISSUE TITLE
The argument "support_email" is required, but no definition was found

### ISSUE THREAD

**Issue by cimnine** [zitadel/terraform-provider-zitadel#119]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

1.0.0-alpha.19

### Describe the problem caused by this bug

```
│ 
│ Error: Missing required argument
│ 
│   on auth.tf line 18, in resource "zitadel_privacy_policy" "internal":
│   18: resource "zitadel_privacy_policy" "internal" {
│ 
│ The argument "support_email" is required, but no definition was found.
│ 
```

Why is this a required attribute? When changing this through the web UI, no support email address must be added.

### To reproduce

1. Add the resource:
   ```tf
   resource "zitadel_privacy_policy" "internal" {
     org_id       = zitadel_org.internal.id
     tos_link     = "https://bla.ch/agb"
     privacy_link = "https://bla.ch/datenschutz"
     help_link    = "https://bla.ch/faq"
   }
   ```
2. `terraform validate`

### Expected behavior

I would expect the required fields of the Zitadel Terraform provider to match the required fields of the web UI.

**Comment by eliobischof** [comment]
I also think the field should be optional :+1:
