### ISSUE TITLE
Add the ability to set the organization as default in zitadel_org resource

### ISSUE THREAD

**Issue by pisarz** [zitadel/terraform-provider-zitadel#121]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

At the moment there is only one attribute to be set when creating a new org.
```
resource "zitadel_org" "org" {
  name = "terraform-test"
}
```

### Describe your ideal solution

It would be really useful if we could choose the organization to be the default one for the instance, i.e.:
```
resource "zitadel_org" "org" {
  name = "terraform-test"
  is_default = true
}
```

### Version

`1.0.0-alpha.18`

**Comment by hifabienne** [comment]
Thank you for sharing your idea.

If there is a significant demand from customers, we will carefully consider implementing the feature.

Currently, the issue will be added to our product backlog.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by vavsab** [comment]
@hifabienne Hi. [I have created a PR](https://github.com/zitadel/terraform-provider-zitadel/pull/136)
Do you know who should I ping to review it?

**Comment by hifabienne** [comment]
> @hifabienne Hi. [I have created a PR](https://github.com/zitadel/terraform-provider-zitadel/pull/136) Do you know who should I ping to review it?

Hei I have added it to our sprint board, and will mention it in our daily.

**Comment by vavsab** [comment]
Thank you @hifabienne 
This change is important for my company. We are migrating away from Auth0 right now.
