### ISSUE TITLE
Ability to start a fresh zitadel instance and configure directly through terraform

### ISSUE THREAD

**Issue by zifeo** [zitadel/terraform-provider-zitadel#13]
Current, it seems required to create a service account, create keys, add iam to zitadel instance to be able to run terraform. I would expect to be able use FirstInstance token/default credentials to automatize the configuration from scratch. This is especially useful in development where instance are destroyed and recreated multiple times.

**Comment by stebenz** [comment]
Currently yes, but there is already an issue #5 which should cover your mentioned functionality.

**Comment by zifeo** [comment]
@stebenz sounds similar, however the pain mostly on the terraform provider authentication. I would love to connect through the root account credentials.

**Comment by stebenz** [comment]
> @stebenz sounds similar, however the pain mostly on the terraform provider authentication. I would love to connect through the root account credentials.

there is already an issue open that the client library used in the terraform provider should be improved [here](https://github.com/zitadel/zitadel-go/issues/130), after this we can look into how the whole process could be best achieved

**Comment by stebenz** [comment]
@zifeo The functionality to create an instance through zitadel-go is resolved.

But there are several other things unfortunately missing, but not on the side of the terraform provider but ZITADEL directly, planned for sometime in the future but I'm not sure when exactly, do you have any direct need for this functionality right now? Like is it a blocker for you until this issue is resolved?

**Comment by zifeo** [comment]
@stebenz Great news! On our side, we will only use Zitadel when we have full environment provisioning (e.g. start from scratch and configuration everything through terraform - especially third-party openid and jwt full configuration) as this is required by our QA processes.

**Comment by stebenz** [comment]
> @stebenz Great news! On our side, we will only use Zitadel when we have full environment provisioning (e.g. start from scratch and configuration everything through terraform - especially third-party openid and jwt full configuration) as this is required by our QA processes.

Functionality is provided on ZITADEL side as documented [here](https://zitadel.com/docs/guides/deploy/compose#docker-compose-with-service-account) will close this issue for the time being, if any question arise please open it again.
