### ISSUE TITLE
Manage user metadata

### ISSUE THREAD

**Issue by vavsab** [zitadel/terraform-provider-zitadel#132]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I can manage user metadata through API but cannot do it through terraform
https://zitadel.com/docs/apis/resources/mgmt/management-service-set-user-metadata

### Describe your ideal solution

```
resource "zitadel_user_metadata" "default" {
  org_id            = data.zitadel_org.default.id
  user_id          =  data.zitadel_user.default.id
  key                = "example"
  value             = "value"
}
```

### Version

1.0.2

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by steled** [comment]
I posted a workaround for those who are interested in: https://github.com/zitadel/terraform-provider-zitadel/issues/29#issuecomment-2077125845
