### ISSUE TITLE
Ability to manage user password

### ISSUE THREAD

**Issue by vavsab** [zitadel/terraform-provider-zitadel#133]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Today I cannot manage user password from Terraform. I can only set an initial password. Furthermore, it must be changed on the first login.

API [can already do everything we need](https://zitadel.com/docs/apis/resources/mgmt/management-service-set-human-password). Just need to use it inside of the TF provider.

### Describe your ideal solution

resource "zitadel_human_user" "default" {
  ...
  password   = "Password1!"
  no_change_required = false
  ...
}

### Version

v1.0.3

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by vavsab** [comment]
Not needed anymore

**Comment by johnmpost** [comment]
I would like this! Specifically to set no_change_required so the user doesn't have to change the password on first login. Or is there a workaround / better solution?
