### ISSUE TITLE
Project field is not documented for the Terraform Provider

### ISSUE THREAD

**Issue by stephenandary** [zitadel/terraform-provider-zitadel#134]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

See <https://registry.terraform.io/providers/zitadel/zitadel/latest/docs#schema> and <https://registry.terraform.io/providers/zitadel/zitadel/latest/docs> 

The lack of a project field in the schema can be misleading, as in some terraform providers, a project id is mandatory (e.g. GCP). 

Is the project mandatory for Zitadel? Does it need to be a specific type?

**Comment by stephenandary** [comment]
Was there a recent refactor where this was moved into a unique resource? <https://registry.terraform.io/providers/zitadel/zitadel/latest/docs/resources/project>

**Comment by hifabienne** [comment]
@stebenz @eliobischof Can you give an answer to this?

**Comment by eliobischof** [comment]
I don't know why there is a project field in the provider example.
Removing it with https://github.com/zitadel/terraform-provider-zitadel/pull/137

**Comment by stebenz** [comment]
@eliobischof I will close your PR, as @stephenandary already mentioned it changed in https://github.com/zitadel/terraform-provider-zitadel/pull/135

**Comment by hifabienne** [comment]
@eliobischof @stebenz Does that mean we can close this issue?

**Comment by eliobischof** [comment]
Yes, the docs are updated with the next release :+1:
