### ISSUE TITLE
label policy add dark mode / light mode only config option

### ISSUE THREAD

**Issue by DerGary** [zitadel/terraform-provider-zitadel#138]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Enable us to completely setup zitadel via terraform.

### Describe your ideal solution

As a developer I want to configure the option to restrict the Zitadel UI to use dark mode only via the label policy or another fitting policy in terraform. Currently to complete the setup you have to log in to the UI and change the Mode to Dark Mode only manually. 

### Version

1.0.4

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.
