### ISSUE TITLE
Data entities

### ISSUE THREAD

**Issue by zifeo** [zitadel/terraform-provider-zitadel#14]
Currently, it seems only possible to create terraform resources. For convenience and development workflow (see #13), I would expect to get read "data" blocks to manage at least org and project.

**Comment by stebenz** [comment]
What do you mean exactly with "read data blocks"?
As in an import functionality as mentioned in #9 ?

**Comment by zifeo** [comment]
@stebenz not really, the official name is [data sources](https://www.terraform.io/language/data-sources).

**Comment by stebenz** [comment]
data sources are available in 1.0.0-alpha.8 for several resources now, just included basic functionality, without filtering, if there would be any need for it, please don't hesitate to open another issue
