### ISSUE TITLE
Auto generate provider for faster release of new endpoints

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/terraform-provider-zitadel#15]
When new endpoints are added to ZITADELs APIs, manual work is needed to implement the changes in the Terraform provider. This adds lag to the Terrafrom provider release.

It could be useful to use tools that automatically generate Terraform resources from gRPC definitions.
Example (never used personally, but could be worth investigating): https://github.com/gravitational/protoc-gen-terraform

**Comment by stebenz** [comment]
> When new endpoints are added to ZITADELs APIs, manual work is needed to implement the changes in the Terraform provider. This adds lag to the Terrafrom provider release.
> 
> It could be useful to use tools that automatically generate Terraform resources from gRPC definitions. Example (never used personally, but could be worth investigating): https://github.com/gravitational/protoc-gen-terraform

I shortly looked at it as I started the implementation, as I understand it, the generation is just for the schema of the resources, you still have to implement all create, update, delete and read functions. So with this in mind, I opted to do it without generation, but maybe I need to take a closer look.

**Comment by stebenz** [comment]
Default policies and custom texts are currently generated with [https://github.com/gravitational/protoc-gen-terraform](https://github.com/gravitational/protoc-gen-terraform), had to include [https://github.com/hashicorp/terraform-plugin-mux](https://github.com/hashicorp/terraform-plugin-mux) as we used terraform SDK before and the generated code is for terraform framework.

Will close this issue, for now, migrating everything over to terraform protocol version 6 with terraform framework will be done step by step.
