### ISSUE TITLE
pulumi zitadel package maintenance

### ISSUE THREAD

**Issue by vavsab** [zitadel/terraform-provider-zitadel#158]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

My company invested time to create [a package for pulumi based on this terraform package](https://github.com/pulumiverse/pulumi-zitadel).
Then we decided to sunset zitadel and do not need pulumi package anymore.

We have 2 options:
1. I archive the repo and people that are using it will not get any updates anymore.
2. I transfer ownership to you if you are interested to support pulumi package.

Supporting does not take a lot of time. Most things are automated. Just need to watch at it from time to time.
We can schedule a call if you want me to share my experience. 

### Describe your ideal solution

Please choose the option you prefer

**Comment by eliobischof** [comment]
Hi @vavsab 

Thank you for your dedication to ZITADEL and for offering to transfer the pulumi package repository as you sunset ZITADEL. We'll review this and get back to you soon.

Have a great weekend!

**Comment by ralf-cestusio** [comment]
As both a Pulumi and Zitadel user i would love if you take over the ownership

**Comment by vavsab** [comment]
@ralf-cestusio nice! We may arrange a meeting if you want me to explain how I do the maintenance in case you have no experience of pulumi package maintenance

**Comment by ralf-cestusio** [comment]
@vavsab I guess there was a small misunderstanding (maybe because  both of our native languages are not English)

I was expressing support for the idea that Zitadel takes over the pulumi provider.

**Comment by vavsab** [comment]
Ah.. sorry. Did not read the end of your comment carefully

**Comment by eliobischof** [comment]
ZITADEL engineer here :-)

We are interested in taking over the provider. @vavsab would you mind sending us your preferred times for a meeting to hi@zitadel.com?

**Comment by vavsab** [comment]
@eliobischof 🔥💥 great news!
Sent my calendar to the email you provided

**Comment by vavsab** [comment]
Ownership has been transferred 🥳
