### ISSUE TITLE
Use booleans instead of strings in the documentation

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/terraform-provider-zitadel#16]
Booleans should be passed as `true` instead of `"true"`.

Example: https://github.com/zitadel/terraform-provider-zitadel/blob/97b2d6c6cf46906ae4a15542bdf1b77bfba129f7/docs/resources/project.md?plain=1#L20

Docs: https://www.terraform.io/language/expressions/types#bools

**Comment by stebenz** [comment]
Correct, I will have a look at it.

**Comment by stebenz** [comment]
corrected examples in 1.0.0-alpha.8
