### ISSUE TITLE
LoginPolicy.hide_password_reset inverts the setting

### ISSUE THREAD

**Issue by ralf-cestusio** [zitadel/terraform-provider-zitadel#168]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

1.1.1

### ZITADEL Version

Cloud

### Describe the problem caused by this bug

Setting hide_password_reset = false 

Disables the password rest allowed option as seen in ui

### To reproduce

Set a loginPolicy with the option set to false

### Expected behavior

Either the hidePasswordReset when set to true should disable password reset. 
Or the option should be renamed to AllowPasswordReset (or similar)

**Comment by ralf-cestusio** [comment]
I looked a bit more through the zitadel source code. And its possible that the bug is on the webui side

**Comment by eliobischof** [comment]
> I looked a bit more through the zitadel source code. And its possible that the bug is on the webui side

This is the case, and it's fixed with https://github.com/zitadel/zitadel/releases/tag/v2.51.4 and deployed to the Cloud
