### ISSUE TITLE
Implementation of Instance/Organization level branding

### ISSUE THREAD

**Issue by DoGab** [zitadel/terraform-provider-zitadel#17]
Being able to configure branding on instance and organization level via Terraform would be great. With the same possbilities as in the UI.

**Comment by stebenz** [comment]
I would guess this would include #7 and #5 , as you would need the policies and custom texts

**Comment by stebenz** [comment]
Will close this issue, as texts and policies are covered with release 1.0.0-alpha.10 , issue #39 is open for specific functionality for images on branding.
