### ISSUE TITLE
Generic OAuth2 IDP provider resource missing on org level

### ISSUE THREAD

**Issue by demircis** [zitadel/terraform-provider-zitadel#172]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

There is no way to specify an generic OAuth2 IDP provider using the terraform provider.

### Describe your ideal solution

Add the missing resource to the terraform provider

### Version

1.1.1

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog to collect feedback.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.
