### ISSUE TITLE
Missing 'skip login success page' option for native app redirect settings

### ISSUE THREAD

**Issue by dmytrum** [zitadel/terraform-provider-zitadel#181]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

1.2.0

### Describe the problem caused by this bug

When creating native app, in redirect settings there is an option 'Skip Login Success Page', but it looks like it missed in tf provider.

### To reproduce

1. Define `zitadel_application_oidc` resource in terraform
2. `skip_login_success_page` is missing

### Screenshots

<img width="969" alt="image" src="https://github.com/zitadel/terraform-provider-zitadel/assets/149471949/30e1b7ab-0154-45ad-9d1f-db18d9e6e730">

**Comment by hifabienne** [comment]
Hi @dmytrum 
Thanks for adding this.
I do not really consider this as a bug, as each attribute has currently to be added manually to the terraform provider when something changes in the api, i see it as an improvement.

I will put it to the small issues/bug fixing state.
Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by dmytrum** [comment]
<img width="693" alt="image" src="https://github.com/zitadel/terraform-provider-zitadel/assets/149471949/e7b6c236-cb02-42e1-bd11-08802f0600d6">
@hifabienne here is another problem I discovered - as you can see 'Skip Login Success Page' is checked. When I adding with terraform 'Redirect URIs' - it return back to unchecked (default state)
