### ISSUE TITLE
Activate smtp config not possible

### ISSUE THREAD

**Issue by yajo10** [zitadel/terraform-provider-zitadel#183]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Hey,
I'm trying to activate a smtp configuration via terraform. I can create a new smtp config via the corresponding terraform resource. 

```
resource zitadel_smtp_config smtp {
  sender_address = var.smtp_sender_address
  sender_name    = var.smtp_sender_name
  tls            = true
  host           = var.smtp_host_port
  user           = var.smtp_login_user
  password       = var.smtp_login_password
}
```

Is there any possibility to activate it within terraform? Currently I always have to log in first and activate the smtp provider manual. 
Thanks in advance.

### Describe your ideal solution

As a administrator I want to be able to activate a smtp configuration.

### Version

1.2.0

### Additional Context

As I asked in the chat https://discord.com/channels/927474939156643850/1246564216769613834 this is currently not possible.

**Comment by FabianKlemmAA** [comment]
Hi! 

We observed another unfortunate effect of this: As long as SMTP provider is _not_ activated, the terraform provider will not recognize the resource to be in place.

As a consequence, when your create a SMTP provider via terraform, it will recreate a new SMTP provider with the same configuration as long as one gets activated with every plan/apply.

Would be great if you could look into that issue! Thank you!

**Comment by stebenz** [comment]
There is a fix in the new version of the provider, please refer to the comment on the release under https://github.com/zitadel/terraform-provider-zitadel/releases/tag/v2.0.0.

I will close this issue for now, if the problem still occurs please reopen it.

**Comment by stebenz** [comment]
> For me this issue still persist. I've tested it with zitadel v2.67.2 and the terraform provider for zitadel has version 2.0.2. Unfortunately, I don't have the permission to reopen the issue.

Does this mean you did the re-import mentioned in https://github.com/zitadel/terraform-provider-zitadel/releases/tag/v2.0.0?
