### ISSUE TITLE
Provider panics when no changes are detected

### ISSUE THREAD

**Issue by buehler** [zitadel/terraform-provider-zitadel#25]
When using the provider to create an OIDC application, some fields are not required (as far as I understand). However, some fields are set in the terraform state which are not configured in the `tf` file.

Thus, on planning the provider wants to remove certain defaulted fields and wants to create an in-place update. But, when executing the update, the ZITADEL API responds with an error that no changes are detected.

Terraform File:
```tf
resource "zitadel_application_oidc" "frontend" {
  org_id     = local.zitadel_org_id
  project_id = zitadel_project.project.id

  name = "Frontend"
  redirect_uris = [
    "http://localhost/signin",
    "http://localhost:3000/signin",
    "http://localhost:3000/oauth2-redirect.html",
    "http://localhost:5000/signin",
    "http://localhost:8080/signin",
  ]
  app_type         = "OIDC_APP_TYPE_WEB"
  response_types   = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types      = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"]
  auth_method_type = "OIDC_AUTH_METHOD_TYPE_NONE"
  clock_skew       = "0s"
  dev_mode         = true
}
```

Terraform Plan:
```
# zitadel_application_oidc.frontend will be updated in-place
  ~ resource "zitadel_application_oidc" "frontend" {
      - access_token_type           = "OIDC_TOKEN_TYPE_BEARER" -> null
        id                          = "181146078928699649"
        name                        = "Frontend"
        # (16 unchanged attributes hidden)
    }
```

Response:
```
Error: failed to update applicationOIDC: rpc error: code = FailedPrecondition desc = No changes (COMMAND-1m88i)
```

I guess it has to do with the information that is returned versus the one that is in the terraform file.

My suggestion would be to ignore "no changes" errors in the provider and just go on.

**Comment by stebenz** [comment]
included in release 1.0.0-alpha.10 so closing issue
