### ISSUE TITLE
Provide ability to authenticate with JSON jwt profile

### ISSUE THREAD

**Issue by buehler** [zitadel/terraform-provider-zitadel#27]
Instead of using a file to point to the JSON jwt profile, it would help to configure the actual JSON value. Then, in CI situations, one can use env vars directly.

So instead of 
```tf
provider "zitadel" {
  domain = local.zitadel_issuer
  token  = var.zitadel_key_path
}
```

```tf
provider "zitadel" {
  domain = local.zitadel_issuer
  token  = var.zitadel_jwt_profile
}
```

Further, I suggest to rename the field to actually mirror the use-case:
`jwt_profile_file` in this case. Then further use-cases may include:
`jwt_profile_json` or `personal_access_token`.

**Comment by stebenz** [comment]
closed as functionality is included in v1.0.0-alpha.14
