### ISSUE TITLE
Add semantic release and dependabot to this repo

### ISSUE THREAD

**Issue by fforootd** [zitadel/terraform-provider-zitadel#3]
As an developer, I want a pipeline with semantic release and dependabot so that with a commit and semrel defined tags new versions of the zitadel provider will get released on the terraform registry and the dependencies used are held up-to-date.

**Acceptance criteria** 

- [ ] Dependabot is included in the pipeline
- [ ] SemRel conform commits result in new releases of the terraform provider
- [ ] New releases of the terraform provider are automatically released to the terraform registry

**Comment by hifabienne** [comment]
From my perspecitve we can close this issue
feel fre to reopen if needed
