### ISSUE TITLE
Login policy defaults do not match

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/terraform-provider-zitadel#37]
The default values of https://registry.terraform.io/providers/zitadel/zitadel/latest/docs/resources/default_login_policy and https://registry.terraform.io/providers/zitadel/zitadel/latest/docs/resources/login_policy do not match with
https://github.com/zitadel/zitadel/blob/47ffa52f0faef028439914b006f124dc4d465751/cmd/defaults.yaml#L417.
It looks like `mfa_init_skip_lifetime` and `multi_factor_check_lifetime` might have been swapped given the ranges

**Comment by stebenz** [comment]
These are only examples, but yes you're right, there was a swap with the values, will correct it.

**Comment by stebenz** [comment]
included in v1.0.0-alpha.11
