### ISSUE TITLE
Select data source by name not id

### ISSUE THREAD

**Issue by DoGab** [zitadel/terraform-provider-zitadel#47]
**Problem:**
Most of the times when selecting a data source you want to select it by name and get the ID so you can reference it elsewhere and use it for other resources. At the Moment it is only possible to select data sources by ID. However if you redeploy Zitadel all IDs change but the name stays the same.

**Solution:**
Make it possible to select data sources by name not by ID.

For now the organization is the most relevant resource, so we will start adding the support there.

**Acceptance Criteria**
- [ ] I am able to select the organizations by name or id

**Comment by eliobischof** [comment]
This is released with [v1.0.0-alpha.19](https://github.com/zitadel/terraform-provider-zitadel/releases/tag/v1.0.0-alpha.19)
