### ISSUE TITLE
Implementation of resources for policies and settings on instance level

### ISSUE THREAD

**Issue by stebenz** [zitadel/terraform-provider-zitadel#5]
Contains:

- [x] Default policy definitions
- [ ] IDP definitions
- [ ] IAM members
- [x] SMTP configuration
- [x] SMS provider configuration

Will be implemented if there is demand.

**Comment by stebenz** [comment]
relates to #24

**Comment by DavideWalder** [comment]
- [ ] security settings

**Comment by stebenz** [comment]
closed due to #49
