### ISSUE TITLE
feature: set org domains as verified and primary

### ISSUE THREAD

**Issue by DoGab** [zitadel/terraform-provider-zitadel#52]
**Problem**
In the ui it is possible to manually verify a domain or set it also as primary domain. In terraform this feature is missing. Also if a domain is added before the `validate_org_domain` setting was disabled, this domain stays unverified.

**Solution**
Make it possible to also set a domain as verified and/or primary with terraform.

**Acceptance Criteria**
- [ ] Terraform provider is able to create verified domains directly
- [ ] Terraform provider is able to create primary domain directly

**Comment by hifabienne** [comment]
To add the verified domains the policy can be set, so domains will be set as verified automatically. 
In the terraform provider the policy can be set as dependency for the domains, so the policy exists when the domains will be created.
So for the moment the most important is to be able to set the primary domains.

**Comment by stebenz** [comment]
included in v1.0.0-alpha.13 with the functionality to set domain as primary, combined with the policy setting to set it to verified it should cover the criteria, otherwise please open a different issue.
