### ISSUE TITLE
TriggerActions to use strings as flow and trigger types

### ISSUE THREAD

**Issue by stebenz** [zitadel/terraform-provider-zitadel#57]
As a administrator, I want to use the terraform provider to manage trigger actions with the respective flow types as strings, not integers, so that it's self-explanatory what it means when you look at the terraform files.

**Acceptance criteria**
- [x] I can manage the trigger actions through terraform
- [x] I can use either integers or strings which get validated in the logic as flow types
- [x] I can use either integers or strings which get validated in the logic as trigger types

**Comment by hifabienne** [comment]
As a workaround for the moment the enum number can be sent

**Comment by stebenz** [comment]
closed as functionality is included in v1.0.0-alpha.14
