### ISSUE TITLE
Feature request: initialize ZITADEL instance from scratch without human interaction

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/terraform-provider-zitadel#8]
**Problem**
There are situations such as:
- automated integration tests
- local frontend development (interacting with a protected resource)

where it must be possible to have a self-contained, reproducible and automated ZITADEL setup that doesn't require human interaction. For example, this setup should be able to reproduce the production setup having the same settings and architecture as well as a dummy user that can be used for local development. This should be achieved by simply running `docker compose up`

**Possible solution**
The terraform provider would be a great candidate for this, but it still requires human interaction (login, change password, create a service user with the correct memberships). Is it planned to be able to use the terraform provider in such a way?

From what I've seen it is currently not possible to create an instance of ZITADEL without human interaction, so this might be outside of the scope of this repo.

**Comment by DavideWalder** [comment]
Let me know if a discussion is more appropriate (instead of an issue)

**Comment by fforootd** [comment]
Thank you for raising this. 

To some degree we can already start zitadel in a reproducible fashion with docker compose or something similar. We do this in our e2e GitHub action pipeline.

But I think we should discuss this further. I will try to get my head around this, this week.

**Comment by DavideWalder** [comment]
> Thank you for raising this.
> 
> To some degree we can already start zitadel in a reproducible fashion with docker compose or something similar. We do this in our e2e GitHub action pipeline.
> 
> But I think we should discuss this further. I will try to get my head around this, this week.

I had a look at it, from what I understood it uses Cypress to get over the initial login and password change. I opted for not using that setup simply because it would need to have one container running Cypress and one running Terraform after that.

I saw in the documentation that it is possible to pass the public key a the system API user in the configuration. I could be useful to have the same thing for an admin machine user having the same permissions as the initial human user. Basically rendering the GUI completely optional.

**Comment by stebenz** [comment]
At least functionality to create instance level resources is already planned in #5, but I think even this is not fully automated as some credentials have to be provided anyway, I will have to have a look at it again afterward.

**Comment by stebenz** [comment]
@DavideWalder The functionality to create an instance through zitadel-go is resolved.

But there are several other things unfortunately missing, but not on the side of the terraform provider but ZITADEL directly, planned for sometime in the future but I'm not sure when exactly, do you have any direct need for this functionality right now? Like is it a blocker for you until this issue is resolved?

**Comment by DavideWalder** [comment]
This is only a blocker for CI pipeline (automated integration tests) and containerized local development, but not for production use.

**Comment by hifabienne** [comment]
Similar to #13

**Comment by stebenz** [comment]
Functionality is provided on ZITADEL side as documented [here](https://zitadel.com/docs/guides/deploy/compose#docker-compose-with-service-account) will close this issue for the time being, if any question arise please open it again.
