### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by eliobischof** [zitadel/terraform-provider-zitadel#85]
As a system admin, I want to use a stable release, so I am confident that the Terraform provider doesn't break my setup with new releases.

**Acceptance Criteria**
- [ ] All resources are automatically testable

**Comment by hifabienne** [comment]
@eliobischof Is this already in progress? As I see there is a pr linked?

**Comment by eliobischof** [comment]
No, it's just the PR that merges alpha to main.
