### ISSUE TITLE
Error when destroying primary zitadel_domain resource

### ISSUE THREAD

**Issue by ilyashtrikul** [zitadel/terraform-provider-zitadel#88]
If zitadel_domain has primary flag, it will not be destroyed.

```hcl
resource zitadel_org my_org {
    name = "My Org Name"
}

resource zitadel_domain primary {
    org_id     = zitadel_org.my_org.id
    name       = "primary.com"
    is_primary = true
}

resource zitadel_domain secondary {
    org_id     = zitadel_org.my_org.id
    name       = "secondary.com"
}
```

When I run terraform destroy on it, I have error.
```
Error: failed to delete domain: rpc error: code = FailedPrecondition desc = Primary domain must not be deleted (ORG-Sjdi3)
```

May be domain should be a block in zitadel_org resource?

---
Provider version: 1.0.0-alpha.16
Zitadel version: 2.23.1

**Comment by hifabienne** [comment]
@stebenz Can you have a look at this?

**Comment by hifabienne** [comment]
Hei @ilyashtrikul 
This has been fixed with the following pr: https://github.com/zitadel/terraform-provider-zitadel/pull/101
I will close the issue, please reopen, if you still encounter problems.
